version: 2
jobs:
    build:
        docker:
            - image: circleci/php:7.4-cli-node-browsers

        working_directory: ~/app

        steps:
            - checkout

            - restore_cache:
                keys:
                    - composer-{{ checksum "composer.json" }}
                    - composer-

            - run:
                name: Disable xdebug
                command: |
                    sudo sed -i 's/^zend_extension/;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

            - run:
                name: Install dependencies
                command: composer install -n --prefer-dist

            - save_cache:
                paths:
                    - ./vendor
                key: composer-{{ checksum "composer.json" }}

            - run:
                name: "Execute all tests"
                command: |
                    set -x

                    mkdir -p ./phpunit
                    export PHPUNIT_ARGS="-v --log-junit ./phpunit/junit.xml"

                    make test

            - store_test_results:
                path: ./phpunit
